defaults:
  - _self_

train_default:
  _target_: torch.utils.data.DataLoader
  batch_size: 2
  shuffle: true
  num_workers: 0
  pin_memory: false

val_default:
  _target_: torch.utils.data.DataLoader
  batch_size: 2
  shuffle: false
  num_workers: 0
  pin_memory: false
