_target_: diffusers.StableDiffusionPipeline.from_pretrained
pretrained_model_name_or_path: ${model.pretrained_model_name_or_path}
torch_dtype: ${model.weight_dtype}
safety_checker: null
requires_safety_checker: false
