train:
  _target_: torchvision.transforms.Compose
  _convert_: partial
  transforms:
    - _target_: src.transforms.pad_resize.PadResize
      size: ${data_source.size_image}
      mode: reflect
    - _target_: torchvision.transforms.RandomHorizontalFlip
      p: 0.5
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]

val:
  _target_: torchvision.transforms.Compose
  _convert_: partial
  transforms:
    - _target_: src.transforms.pad_resize.PadResize
      size: ${data_source.size_image}
      mode: reflect
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
